config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :images
    resources :favorites, only: [:index, :create]
  end
  resources :images, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [:create]
  end

  root to: "home#index"
  get '/user/profile' => "users#profile"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :image


  def find_author
    author = User.find(self.author_id)
    return author.username
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :tags
  has_and_belongs_to_many :favorited_by_users, class_name:"User"

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/tag.rb
class Tag <ActiveRecord::Base
  belongs_to :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :images
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,
                    :styles => {
                                :medium => "300x300>",
                                :thumb => "1--X100#"},
                                :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_and_belongs_to_many :favorited_images, class_name:"Image"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # important
  # before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def is_image_owner
    image = Image.find(params[:id])
    user = User.find(params[:user_id])
    if !current_user
      flash[:alert] = "Please login"
      redirect_to new_user_session_path
    elsif current_user.id != image.user_id
      flash[:alert] = 'You are not authorized to edit this image'
      redirect_to user_image_path(user, image)
    end
  end
  protected

  def configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:image, :email, :password) }
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :avatar, :password])
    # devise_parameter_sanitizer.permit(:account_update, keys: [:email, :avatar, :password, :current_password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @image = Image.find(params[:id])
    @comment = @image.comments.new
  end

  def create
    @image = Image.find(params[:image_id])
    @comment = @image.comments.new(comment_params)
    if @comment.save
      @comment.author_id = current_user.id
      redirect_to user_image_path(@image.user, @image)
    else
      redirect_to user_image_path(@image.user, @image)
    end
  end

private
  def comment_params
    params.require(:comment).permit(:content, :author_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController<ApplicationController
  def index
    @favorites = current_user.favorited_images
  end

  def create
    @user = User.find(params[:user_id])
    @image = Image.find(params[:image_id])
    if @user.favorited_images.exclude?(@image)
      @user.favorited_images.push(@image)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @images = Image.all
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :is_image_owner, only:[:edit, :destroy]
  def show
    @image = Image.find(params[:id])
    @comment = Comment.new
  end

  def new
    @image = Image.new
  end

  def create
    @image = current_user.images.new(image_params)
    if @image.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def update
    @image = current_user.images.find(params[:id])
    if @image.update(image_params)
      redirect_to user_image_path(current_user, @image)
    else
      render :edit
    end
  end

  def destroy
    @image = current_user.images.find(params[:id])
    @image.destroy
    redirect_to root_path
  end

private
  def image_params
    params.require(:image).permit(:image, :title)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @image = Image.find(params[:id])
    @tag = Tag.new
  end

  def create
    @image = Image.find(params[:image_id])
    name_array = params[:tags].split
    name_array.each do |name|
      # if !(Tag.all.detect{|tag| tag.name == name})
      if !(@image.tags.detect{|tag| tag.name == name})
        new_tag = Tag.create(name: name)
        @image.tags.push(new_tag)
      end
    end
    redirect_to user_image_path(@image.user, @image)
  end
private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    render :posts

  end
  
  def profile
    render :profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [@image, @comment] do |form| %>
  <%= form.label :content %>
  <%= form.text_field :content %>
  <%= form.hidden_field :author_id, value: current_user.id %>
  <%= form.submit "Add Comment" %>
<% end %>

app/views/favorites/index.html.erb
<% @favorites.each do |image| %>
  <div class="image-div">
    <%= image_tag image.image.url(:medium), class: "img-responsive" %>
    <%= link_to image.title, user_image_path(image.user_id, image) %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>EpiFlickr</h1>

<h3>Browse Images</h3>
<div class="image-list">
  <% @images.each do |image| %>
    <div class="image-div">
      <%= image_tag image.image.url(:medium), class: "img-responsive" %>
      <%= link_to image.title, user_image_path(image.user_id, image) %>
      <% if current_user %>
        <%= form_tag user_favorites_path(current_user) do %>
        <%= hidden_field_tag :image_id, image.id %>
        <%= submit_tag "Favorite!!" %>
      <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/images/edit.html.erb
<h3>Edit the Image</h3>
<%= form_for [current_user, @image], html: { multipart: true } do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.file_field :image %>
  <%= form.submit "Upload" %>
<% end %>

app/views/images/new.html.erb
<h3>Add a New Image</h3>
<%= form_for [current_user, @image], url: user_images_path, html: { multipart: true } do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.file_field :image %>
  <%= form.submit "Upload" %>
<% end %>

app/views/images/show.html.erb
<% if @image.tags.any? %>
<ul>
  <% @image.tags.each do |tag| %>
  <li style="display: inline-block"><%= tag.name %></li>
  <% end %>
</ul>
<%end%>

<%= image_tag @image.image.url(:medium) %>

<%=@image.title %>

<% if current_user.id == @image.user_id %>
  <%= link_to "Edit Image", edit_user_image_path(current_user, @image) %>
  <%= link_to "Delete", user_image_path(current_user, @image), :data => {:confirm => "You sure?",                             :method => "delete"} %>
  <%= form_tag image_tags_path(@image) do %>
    <%= label_tag :tags %>
    <%= text_field_tag :tags %>
    <%= submit_tag "Add Tags" %>
  <% end %>
<% end %>

<h3>Add a New Comment</h3>
<%= render 'comments/form' %>

<% if @image.comments.any? %>
<h3>All Comments</h3>
  <% @image.comments.each do |comment| %>
    <p><%= comment.find_author%></p>
    <p><%= comment.content %></p>
    <p><%= comment.created_at%></p>
  <% end %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Epiflickr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "My Profile ", user_profile_path(current_user) %></li>
            <li><%= link_to "My Pictures ", user_path(current_user) %></li>
            <li><%= link_to "Upload an Image ", new_user_image_path(current_user) %></li>
            <li><%= link_to "Favorites ", user_favorites_path(current_user) %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <%else%>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path%></li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tags/new.html.erb
<h2>New Tag</h2>

app/views/users/posts.html.erb
<% if current_user.images.any? %>
  <h3><%= current_user.username%>'s Uploaded Images<h3>
  <div class="image-list">
    <% current_user.images.each do |image| %>
    <div class="image-div">
      <%= image_tag image.image.url(:medium) %>
      <%= link_to image.title, user_image_path(current_user, image) %>
    </div>
    <% end %>
  </div>
<%else%>
  <h3>You have not uploaded any images</h3>
<%end%>

app/views/users/profile.html.erb
<h1>Username: <%= current_user.username%></h1>
<h1>Email: <%= current_user.email %></h1>
<%= image_tag current_user.avatar.url(:medium) %>